import { image } from "motion/react-client";
import Categories from "../pages/categories";

const data = {
  categories: [
    {
      name: { en: "Cars", ar: "سيارات" },
      items: [
        { en: "Toyota Camry", ar: "تويوتا كامري" },
        { en: "Ford Mustang", ar: "فورد موستانج" },
        { en: "Mercedes G-Class", ar: "مرسيدس جي كلاس" },
        { en: "Nissan Patrol", ar: "نيسان باترول" },
        { en: "Tesla Model 3", ar: "تسلا موديل 3" },
        { en: "Range Rover Sport", ar: "رينج روفر سبورت" },
        { en: "Honda Civic", ar: "هوندا سيفيك" },
        { en: "Porsche 911", ar: "بورشه 911" },
        { en: "Chevrolet Tahoe", ar: "شيفروليه تاهو" },
        { en: "BMW M5", ar: "بي إم دبليو M5" },
        { en: "Lexus LS", ar: "لكزس LS" },
        { en: "Dodge Charger", ar: "دوج تشارجر" },
        { en: "Audi A8", ar: "أودي A8" },
        { en: "Jeep Wrangler", ar: "جيب رانجلر" },
        { en: "Lamborghini Urus", ar: "لامبورغيني أوروس" },
      ],
      image: `Cars.png`,
    },
    {
      name: { en: "Cartoons", ar: "كرتون" },
      items: [
        { en: "Tom and Jerry", ar: "توم وجيري" },
        { en: "Mickey Mouse", ar: "عدنان ولينا" },
        { en: "SpongeBob SquarePants", ar: "سبيس تون" },
        { en: "The Simpsons", ar: "كابتن ماجد" },
        { en: "Batman: The Animated Series", ar: "جريندايزر" },
        { en: "Scooby-Doo", ar: "بوكيمون" },
        { en: "Looney Tunes", ar: "سالي" },
        { en: "Avatar: The Last Airbender", ar: "المحقق كونان" },
        { en: "Ben 10", ar: "سابق ولاحق" },
        { en: "The Powerpuff Girls", ar: "ريمي" },
        { en: "Teen Titans", ar: "ماوكلي" },
        { en: "Adventure Time", ar: "النمر المقنع" },
        { en: "Dragon Ball Z", ar: "دراغون بول" },
        { en: "Spider-Man", ar: "أبطال الديجيتال" },
        { en: "The Lion King", ar: "عهد الأصدقاء" },
      ],
      image: `Cartoons.png`,
    },
    {
      name: { en: "Animals", ar: "حيوانات" },
      items: [
        { en: "Lion", ar: "أسد" },
        { en: "Tiger", ar: "نمر" },
        { en: "Elephant", ar: "فيل" },
        { en: "Giraffe", ar: "زرافة" },
        { en: "Zebra", ar: "حمار وحشي" },
        { en: "Camel", ar: "جمل" },
        { en: "Wolf", ar: "ذئب" },
        { en: "Fox", ar: "ثعلب" },
        { en: "Monkey", ar: "قرد" },
        { en: "Rabbit", ar: "أرنب" },
        { en: "Deer", ar: "غزال" },
        { en: "Eagle", ar: "صقر" },
        { en: "Dolphin", ar: "دلفين" },
        { en: "Snake", ar: "ثعبان" },
        { en: "Bear", ar: "دب" },
      ],
      image: `Animals.png`,
    },
    {
      name: { en: "Clothes", ar: "ملابس" },
      items: [
        { en: "Shirt", ar: "قميص" },
        { en: "Jeans", ar: "بنطلون جينز" },
        { en: "Jacket", ar: "سترة" },
        { en: "Dress", ar: "فستان" },
        { en: "Suit", ar: "بدلة" },
        { en: "Coat", ar: "معطف" },
        { en: "Sweater", ar: "كنزة" },
        { en: "Skirt", ar: "تنورة" },
        { en: "Hoodie", ar: "هودي" },
        { en: "Abaya", ar: "عباءة" },
        { en: "Thobe", ar: "ثوب" },
        { en: "Tie", ar: "ربطة عنق" },
        { en: "Scarf", ar: "وشاح" },
        { en: "Hat", ar: "قبعة" },
        { en: "Blouse", ar: "بلوزة" },
      ],
      image: `Clothes.png`,
    },
    {
      name: { en: "Meals", ar: "وجبات" },
      items: [
        { en: "Cheeseburger", ar: "كبسة" },
        { en: "Pepperoni Pizza", ar: "منسف" },
        { en: "Steak and Fries", ar: "كشري" },
        { en: "Chicken Alfredo", ar: "ملوخية" },
        { en: "Tacos", ar: "مندي" },
        { en: "Fish and Chips", ar: "طعمية" },
        { en: "Lasagna", ar: "مقلوبة" },
        { en: "Hot Dog", ar: "برياني" },
        { en: "Pancakes", ar: "شاورما" },
        { en: "Caesar Salad", ar: "فتة" },
        { en: "Sushi Roll", ar: "مسقعة" },
        { en: "Beef Burrito", ar: "محشي ورق عنب" },
        { en: "BBQ Ribs", ar: "كفتة" },
        { en: "Mac and Cheese", ar: "مضغوط" },
        { en: "Omelette", ar: "حمام محشي" },
      ],
      image: `Meals.png`,
    },
    {
      name: { en: "Jobs", ar: "وظائف" },
      items: [
        { en: "Doctor", ar: "طبيب" },
        { en: "Engineer", ar: "مهندس" },
        { en: "Teacher", ar: "معلم" },
        { en: "Lawyer", ar: "محامي" },
        { en: "Pilot", ar: "طيار" },
        { en: "Nurse", ar: "ممرض" },
        { en: "Accountant", ar: "محاسب" },
        { en: "Chef", ar: "طباخ" },
        { en: "Architect", ar: "مهندس معماري" },
        { en: "Journalist", ar: "صحفي" },
        { en: "Programmer", ar: "مبرمج" },
        { en: "Pharmacist", ar: "صيدلي" },
        { en: "Policeman", ar: "شرطي" },
        { en: "Artist", ar: "فنان" },
        { en: "Dentist", ar: "طبيب أسنان" },
      ],
      image: `Jobs.png`,
    },
    {
      name: { en: "Movies", ar: "أفلام" },
      items: [
        { en: "The Godfather", ar: "الناصر صلاح الدين" },
        { en: "Inception", ar: "الكيت كات" },
        { en: "Pulp Fiction", ar: "الإرهابي" },
        { en: "The Dark Knight", ar: "الأرض" },
        { en: "Titanic", ar: "باب الحديد" },
        { en: "Gladiator", ar: "شيء من الخوف" },
        { en: "Interstellar", ar: "الفيل الأزرق" },
        { en: "The Matrix", ar: "عمارة يعقوبيان" },
        { en: "Braveheart", ar: "ولاد رزق" },
        { en: "Jurassic Park", ar: "كيرة والجن" },
        { en: "Avatar", ar: "المشبوه" },
        { en: "Joker", ar: "الهروب" },
        { en: "Star Wars", ar: "المنسي" },
        { en: "The Avengers", ar: "طباخ الريس" },
        { en: "Goodfellas", ar: "جعلوني مجرماً" },
      ],
      image: `Movies.png`,
    },
    {
      name: { en: "Places", ar: "أماكن" },
      items: [
        { en: "Eiffel Tower", ar: "برج إيفل" },
        { en: "Burj Khalifa", ar: "برج خليفة" },
        { en: "Great Wall of China", ar: "سور الصين العظيم" },
        { en: "Pyramids of Giza", ar: "أهرامات الجيزة" },
        { en: "Statue of Liberty", ar: "تمثال الحرية" },
        { en: "Colosseum", ar: "الكولوسيوم" },
        { en: "Machu Picchu", ar: "ماتشو بيتشو" },
        { en: "Petra", ar: "البتراء" },
        { en: "Taj Mahal", ar: "تاج محل" },
        { en: "Big Ben", ar: "بيج بن" },
        { en: "Grand Canyon", ar: "الأخدود العظيم" },
        { en: "Alhambra Palace", ar: "قصر الحمراء" },
        { en: "Santorini", ar: "سانتوريني" },
        { en: "Niagara Falls", ar: "شلالات نياجرا" },
        { en: "Mount Everest", ar: "جبل إيفرست" },
      ],
      image: `Places.png`,
    },
    {
      name: { en: "Football Players", ar: "لاعبي كرة قدم" },
      items: [
        { en: "Lionel Messi", ar: "محمد صلاح" },
        { en: "Cristiano Ronaldo", ar: "رياض محرز" },
        { en: "Kylian Mbappé", ar: "أشرف حكيمي" },
        { en: "Erling Haaland", ar: "ياسين بونو" },
        { en: "Kevin De Bruyne", ar: "سالم الدوسري" },
        { en: "Neymar Jr", ar: "إسماعيل بن ناصر" },
        { en: "Luka Modrić", ar: "حكيم زياش" },
        { en: "Robert Lewandowski", ar: "عمر السومة" },
        { en: "Harry Kane", ar: "يوسف النصيري" },
        { en: "Jude Bellingham", ar: "بغداد بونجاح" },
        { en: "Vinícius Júnior", ar: "نايف أكرد" },
        { en: "Mohamed Salah", ar: "سفيان أمرابط" },
        { en: "Zinedine Zidane", ar: "ماجد عبد الله" },
        { en: "Diego Maradona", ar: "محمود الخطيب" },
        { en: "Pelé", ar: "محمد أبو تريكة" },
      ],
      image: `Football_Players.png`,
    },
    {
      name: { en: "Famous Actors", ar: "ممثلين مشهورين" },
      items: [
        { en: "Leonardo DiCaprio", ar: "عادل إمام" },
        { en: "Brad Pitt", ar: "أحمد زكي" },
        { en: "Tom Cruise", ar: "نور الشريف" },
        { en: "Robert De Niro", ar: "محمود ياسين" },
        { en: "Denzel Washington", ar: "فاتن حمامة" },
        { en: "Johnny Depp", ar: "سعاد حسني" },
        { en: "Morgan Freeman", ar: "كريم عبد العزيز" },
        { en: "Angelina Jolie", ar: "أحمد عز" },
        { en: "Meryl Streep", ar: "منى زكي" },
        { en: "Tom Hanks", ar: "يسرا" },
        { en: "Will Smith", ar: "قصي خولي" },
        { en: "Julia Roberts", ar: "باسل خياط" },
        { en: "The Rock", ar: "تيم حسن" },
        { en: "Scarlett Johansson", ar: "هند صبري" },
        { en: "Al Pacino", ar: "رشدي أباظة" },
      ],
      image: `Famous_Actors.png`,
    },
    {
      name: { en: "Makeup", ar: "مكياج" },
      items: [
        { en: "Lipstick", ar: "أحمر شفاه" },
        { en: "Mascara", ar: "ماسكارا" },
        { en: "Foundation", ar: "كريم أساس" },
        { en: "Eyeliner", ar: "كحل" },
        { en: "Blush", ar: "بشرة (بلاشر)" },
        { en: "Eyeshadow", ar: "ظلال العيون" },
        { en: "Concealer", ar: "خافي عيوب" },
        { en: "Highlighter", ar: "إضاءة" },
        { en: "Primer", ar: "برايمر" },
        { en: "Setting Spray", ar: "مثبت مكياج" },
        { en: "Bronzer", ar: "برونزر" },
        { en: "Eyebrow Pencil", ar: "قلم حواجب" },
        { en: "Lip Gloss", ar: "ملمع شفاه" },
        { en: "Face Powder", ar: "بودرة وجه" },
        { en: "Makeup Brushes", ar: "فرش مكياج" },
      ],
      image: `Makeup.png`,
    },
  ],
};

export default data;

